[database]
    host="db"
    user="flahmingo"
    password="flahmingo"
    port="5432"
    name="flahmingo"
[logging]
    level="TRACE"
[server]
    listen="0.0.0.0:9090"

[googleCloud]
    projectID = ""

[twilio]
    accountSid  = ""
    authToken = ""
    phoneNumber = ""
